name: Python application

on:
  pull_request:
    branches:
      - test

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          python3 test_file.py

  notify:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Notify developers of test results
        run: |
          # You can use this step to notify developers of test results, e.g., send a Slack message or email.
          echo "Test results: ${{ job.status }}" # This will print the test status to the workflow log

      - name: Push changes to main branch
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff test # Merge the changes from the test branch to main
          git push origin main
